--TABLA TIPO DE GASTOS
CREATE TABLE "FACTURACION".tb_tipos_gastos(
g_id_gasto SERIAL PRIMARY KEY NOT NULL,
g_descripcion VARCHAR(100) NOT NULL,
g_estado BIT NOT NULL,
g_fecha_ingreso TIMESTAMP WITH TIME ZONE NOT NULL,
g_fecha_actualizacion TIMESTAMP WITH TIME ZONE,
g_usuario VARCHAR(25) NOT NULL,
g_terminal VARCHAR(25) NOT NULL	
)

INSERT INTO "FACTURACION".tb_tipos_gastos
(
g_descripcion,
g_estado,
g_fecha_ingreso,
g_fecha_actualizacion,
g_usuario,
g_terminal
)
VALUES ('00-NO ESPECIFICADO','1',NOW(),NULL,'SA','SA'),
       ('01-GASTOS DE PERSONAL','1',NOW(),NULL,'SA','SA'),
       ('02-GASTOS POR TRABAJOS, SUMINISTROS Y SERVICIOS','1',NOW(),NULL,'SA','SA'),
	   ('03-ARRENDAMIENTOS','1',NOW(),NULL,'SA','SA'),
	   ('04-GASTOS DE ACTIVOS FIJOS','1',NOW(),NULL,'SA','SA'),
	   ('05-GASTOS DE REPRESENTACIÓN','1',NOW(),NULL,'SA','SA'),
	   ('06-OTRAS DEDUCCIONES ADMITIDAS','1',NOW(),NULL,'SA','SA'),
	   ('07-GASTOS FINANCIEROS','1',NOW(),NULL,'SA','SA'),
	   ('08-GASTOS EXTRAORDINARIOS','1',NOW(),NULL,'SA','SA'),
	   ('09-COMPRAS Y GASTOS QUE FORMAN PARTE DEL COSTO DE VENTA','1',NOW(),NULL,'SA','SA'),
	   ('10-ADQUISICIONES DE ACTIVOS','1',NOW(),NULL,'SA','SA'),
	   ('11-GASTOS DE SEGUROS','1',NOW(),NULL,'SA','SA')
       -- PREGUNTA: LAS VENTAS SOLO GENERAN ITBIS ,NINGUN OTRO IMPUESTO?