
--TIPOS CONTACTOS

CREATE TABLE "CONTACTOS".tipoContactos(
id SERIAL PRIMARY KEY NOT NULL,
"tipoContacto" VARCHAR(25)NOT NULL,
estado BIT NOT NULL,
"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
"updateAt" TIMESTAMP WITH TIME ZONE,
usuario VARCHAR(25) NOT NULL,
terminal VARCHAR(25) NOT NULL,

)

