-- ESQUEMA *CUENTAS*
--TABLA CUENTAS CONTABLES PADRES
CREATE TABLE "CUENTAS"."cuentasContablesPadres"
(
id SERIAL PRIMARY KEY NOT NULL,
"noCuenta" INT NOT NULL,
descripcion VARCHAR(50) NOT NULL,
"cuentaPadre" INT NOT NULL DEFAULT 0,
"idEmpresa" INT NOT NULL,
estado BIT NOT NULL,
"createdAt" TIMESTAMP,
"updatedAt" TIMESTAMP ,
usuario VARCHAR(25) NOT NULL,
terminal VARCHAR(25) NOT NULL,	
CONSTRAINT PK_EMPRESA
FOREIGN KEY ("idEmpresa") 
REFERENCES "EMPRESA".empresas(id)

)

--INSERT TABLA CUENTAS CONTABLES PADRES
INSERT INTO "CUENTAS"."cuentasContablesPadres" (
	"noCuenta", 
	descripcion, 
	"cuentaPadre", 
	"idEmpresa", 
	estado, 
	"createdAt", 
	"updatedAt", 
	usuario, 
	terminal
		) 
VALUES 
 (1,'ACTIVOS',0,1,'1',NOW(),NULL,'SA','SA'), --1

 (10,'ACTIVOS CORRIENTES',1,1,'1',NOW(),NULL,'SA','SA'),--2

 (11,'CUENTAS POR COBRAR',1,1,'1',NOW(),NULL,'SA','SA'),--3

 (12,'INVERSIONES',1,1,'1',NOW(),NULL,'SA','SA'),--4
													
 (13,'ACTIVOS FIJOS',1,1,'1',NOW(),NULL,'SA','SA'),--5

 (14,'ACTIVOS DIFERIDOS',1,1,'1',NOW(),NULL,'SA','SA'),--6
													
 (15,'OTROS ACTIVOS',1,1,'1',NOW(),NULL,'SA','SA'),--7

 (2,'PASIVOS',0,1,'1',NOW(),NULL,'SA','SA'),--8

 (20,'PASIVOS CORRIENTES',8,1,'1',NOW(),NULL,'SA','SA'),--9

 (200,'SOBREGIRO BANCARIO ',9,1,'1',NOW(),NULL,'SA','SA'),--10

 (201,'CUENTAS POR PAGAR',9,1,'1',NOW(),NULL,'SA','SA'),--11

 (202,'PRESTAMOS POR PAGAR',9,1,'1',NOW(),NULL,'SA','SA'),--12

 (203,'IMPUESTOS SOBRE LA RENTA POR PAGAR',9,1,'1',NOW(),NULL,'SA','SA'),--13

 (204,'DIVIDENDOS DECLARADOS POR PAGAR',9,1,'1',NOW(),NULL,'SA','SA'),--14

 (205,'RETENCIONES Y ACUMULACIONES POR PAGAR',9,1,'1',NOW(),NULL,'SA','SA'),--15

 (3,'CAPITAL',0,1,'1',NOW(),NULL,'SA','SA'),--16

 (4,'INGRESOS',0,1,'1',NOW(),NULL,'SA','SA'),--17

 (5,'COSTOS',0,1,'1',NOW(),NULL,'SA','SA'),--18

 (6,'GASTOS',0,1,'1',NOW(),NULL,'SA','SA'),--19

 (60,'GASTOS GENERALES Y ADMINISTRATIVOS',19,1,'1',NOW(),NULL,'SA','SA'),--20

 (61,'MANTENIMIENTO MOBILIARIOS Y EQUIPO DE OFICINA',19,1,'1',NOW(),NULL,'SA','SA'),--21
	
 (62,'GASTOS FINANCIAMIENTOS',19,1,'1',NOW(),NULL,'SA','SA'),--22

 (7,'RESUMENES',0,1,'1',NOW(),NULL,'SA','SA')--23
RETURNING *

--VER TODAS LAS CUENTAS

SELECT  
C."noCuenta"   AS NUMERO_CUENTA ,
C.descripcion AS DESCRIPCION ,
COALESCE((SELECT CC.descripcion FROM "CUENTAS"."cuentasContablesPadres" AS CC 
 WHERE C."cuentaPadre" = CC.id ),'RAIZ') AS CUENTA_PADRE 
FROM "CUENTAS"."cuentasContablesPadres" AS C

--CATALOGO CUENTAS

CREATE TABLE "CUENTAS"."cuentasContables"(
id SERIAL PRIMARY KEY NOT NULL,
cuenta VARCHAR(25)NOT NULL,
"idCuentaPadre" INT,
descripcion VARCHAR(50) NOT NULL,
"idEmpresa" INT,
"idMoneda" INT,
estado BIT NOT NULL,
"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
"updateAt" TIMESTAMP WITH TIME ZONE,
usuario VARCHAR(25) NOT NULL,
terminal VARCHAR(25) NOT NULL,
	
	CONSTRAINT PK_ID_EMPRESA
	FOREIGN KEY ("idEmpresa")
	REFERENCES "EMPRESA".empresas(id),

	CONSTRAINT PK_ID_MONEDA
    FOREIGN KEY ("idMoneda")
    REFERENCES  "FACTURACION".monedas(id),
	
	CONSTRAINT PK_ID_CUENTA_PADRE
	FOREIGN KEY ("idCuentaPadre")
	REFERENCES "CUENTAS"."cuentasContablesPadres"(id)
)
--