export * from "./clientes.type";
export * from "./cuentaContable.type";
export * from "./entradaContable.type";
export * from "./facturasPorPagar.type";
export * from "./impuestos.type";
export * from "./proveedor.type";
export * from "./tipoGenerico.type";
export * from "./comun.type";
export * from "./contacto.type";
